models/Category.php
<?php
/**
 * Created by PhpStorm.
 * User: Наталия
 * Date: 22.11.2017
 * Time: 18:29
 */

namespace app\models;

use yii\db\ActiveRecord;

class Category extends ActiveRecord
{
    public static function tableName()
    {
        return 'category';
    }

    public function getProducts()
    {
        return $this->hasMany(Product::className(), ['category_id' => 'id']);
    }
}

controllers/CategoryController.php
<?php
namespace app\controllers;

use app\models\Category;
use app\models\Product;
use yii\data\Pagination;
use yii\web\HttpException;

class CategoryController extends AppController
{
    public $title = 'Мой могазин';

    public function actionIndex()
    {
        $hits = Product::find()->where(['hit' => '1'])->limit(6)->all();
        $this->setMeta($this->title);

        return $this->render('index', compact('hits'));
    }

    public function actionView($id)
    {
        $category = Category::findOne($id);

        if(empty($category))
        {
            throw new HttpException(404, 'Страница категории не най дена!');
        }

        $this->setMeta($this->title . '|' . $category->name, $category->keywords, $category->description);

        $query = Product::find()->where(['category_id' => $id]);
        $countQuery = clone $query;
        $pages = new Pagination([
            'totalCount' => $countQuery->count(),
            'pageSize' => 3,
            'forcePageParam' => false,
            'pageSizeParam'=> false,
        ]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();

        return $this->render('view', [
            'category' => $category,
            'products' => $products,
            'pages' => $pages,
        ]);
    }
    
    public function actionSearch($q)
    {
        $q = trim($q);
        $this->setMeta($this->title . ' | Поиск ' . $q);

        if(!$q)
        {
            return $this->render('search');
        }

        $query = Product::find()->where(['like', 'name', $q]);
        $pages = new Pagination([
            'totalCount' => $query->count(),
            'pageSize' => 3,
            'forcePageParam' => false,
            'pageSizeParam'=> false,
        ]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();

        return $this->render('search', compact('products', 'pages', 'q'));
    }
    
}

controllers/ProductController.php
<?php
/**
 * Created by PhpStorm.
 * User: Наталия
 * Date: 24.11.2017
 * Time: 10:08
 */

namespace app\controllers;

use app\models\Product;
use yii\web\HttpException;

class ProductController extends AppController
{
    public $title = "Карточка продукта";

    public function actionView($id)
    {
        $product = Product::findOne($id);

        if(empty($product))
        {
            throw new HttpException(404, 'Страница продукта не найдена!');
        }

        $hits = Product::find()->where(['hit' => '1'])->limit(6)->all();

        $this->setMeta($this->title . '|' . $product->name, $product->keywords, $product->description);

        return $this->render('view', compact('product', 'hits'));
    }
    
}

views/category/search.php
<?php
use app\components\MenuWidget;
use yii\helpers\Url;
use yii\widgets\LinkPager;
use yii\helpers\Html;

?>

<section id="advertisement">
    <div class="container">
        <img src="/images/shop/advertisement.jpg" alt="" />
    </div>
</section>

<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="left-sidebar">
                    <h2>Category</h2>

                    <ul class="catalog category-products">
                        <?= MenuWidget::widget(['tpl' => 'menu']) ?>
                    </ul>

                    <div class="brands_products"><!--brands_products-->
                        <h2>Brands</h2>
                        <div class="brands-name">
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href=""> <span class="pull-right">(50)</span>Acne</a></li>
                                <li><a href=""> <span class="pull-right">(56)</span>Grüne Erde</a></li>
                                <li><a href=""> <span class="pull-right">(27)</span>Albiro</a></li>
                                <li><a href=""> <span class="pull-right">(32)</span>Ronhill</a></li>
                                <li><a href=""> <span class="pull-right">(5)</span>Oddmolly</a></li>
                                <li><a href=""> <span class="pull-right">(9)</span>Boudestijn</a></li>
                                <li><a href=""> <span class="pull-right">(4)</span>Rösch creative culture</a></li>
                            </ul>
                        </div>
                    </div><!--/brands_products-->

                    <div class="price-range"><!--price-range-->
                        <h2>Price Range</h2>
                        <div class="well">
                            <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
                            <b>$ 0</b> <b class="pull-right">$ 600</b>
                        </div>
                    </div><!--/price-range-->

                    <div class="shipping text-center"><!--shipping-->
                        <img src="/images/home/shipping.jpg" alt="" />
                    </div><!--/shipping-->

                </div>
            </div>
            <div class="col-sm-9 padding-right">
                <div class="features_items"><!--features_items-->
                    <h2 class="title text-center">Поиск по запросу: <?= Html::encode($q) ?></h2>
                    <div class="row">
                        <?php if(!empty($products)): ?>
                            <?php $i = 0; foreach($products as $product): ?>
                                <?php $i++; if($i%3 === 0): ?>
                                    <div class="row">
                                <?php endif; ?>
                                <div class="col-sm-4">
                                    <div class="product-image-wrapper">
                                        <div class="single-products">
                                            <div class="productinfo text-center">
                                                <?=Html::img('@web/images/products/' . $product->img, ['alt' => $product->name])?>
                                                <h2>$<?= $product->price ?></h2>
                                                <p><a href="<?= Url::to(['product/view', 'id' => $product->id]) ?>"><?= $product->name ?></a></p>
                                                <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                            <?php if($product->new): ?>
                                                <?= Html::img("@web/images/home/new.png", ['alt' => 'Новинка', 'class' => 'new']) ?>
                                            <?php endif; ?>
                                            <?php if($product->sale): ?>
                                                <?= Html::img("@web/images/home/sale.png", ['alt' => 'Разпродажа', 'class' => 'new']) ?>
                                            <?php endif; ?>
                                        </div>
                                        <div class="choose">
                                            <ul class="nav nav-pills nav-justified">
                                                <li><a href=""><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                                                <li><a href=""><i class="fa fa-plus-square"></i>Add to compare</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <?php if($i%3 === 0): ?>
                                    </div>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <h2>Ничего не найдено</h2>
                        <?php endif; ?>
                    </div>

                    <?php if(isset($pages)): ?>
                        <div class="row">
                            <?= LinkPager::widget([
                                'pagination' => $pages,
                            ]); ?>
                        </div>
                    <?php endif; ?>

                </div><!--features_items-->
            </div>
        </div>
    </div>
</section>

views/category/view.php
<?php
use app\components\MenuWidget;
use yii\helpers\Url;
use yii\widgets\LinkPager;
use yii\helpers\Html;

?>

<section id="advertisement">
    <div class="container">
        <img src="/images/shop/advertisement.jpg" alt="" />
    </div>
</section>

<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="left-sidebar">
                    <h2>Category</h2>

                    <ul class="catalog category-products">
                        <?= MenuWidget::widget(['tpl' => 'menu']) ?>
                    </ul>

                    <div class="brands_products"><!--brands_products-->
                        <h2>Brands</h2>
                        <div class="brands-name">
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href=""> <span class="pull-right">(50)</span>Acne</a></li>
                                <li><a href=""> <span class="pull-right">(56)</span>Grüne Erde</a></li>
                                <li><a href=""> <span class="pull-right">(27)</span>Albiro</a></li>
                                <li><a href=""> <span class="pull-right">(32)</span>Ronhill</a></li>
                                <li><a href=""> <span class="pull-right">(5)</span>Oddmolly</a></li>
                                <li><a href=""> <span class="pull-right">(9)</span>Boudestijn</a></li>
                                <li><a href=""> <span class="pull-right">(4)</span>Rösch creative culture</a></li>
                            </ul>
                        </div>
                    </div><!--/brands_products-->

                    <div class="price-range"><!--price-range-->
                        <h2>Price Range</h2>
                        <div class="well">
                            <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
                            <b>$ 0</b> <b class="pull-right">$ 600</b>
                        </div>
                    </div><!--/price-range-->

                    <div class="shipping text-center"><!--shipping-->
                        <img src="/images/home/shipping.jpg" alt="" />
                    </div><!--/shipping-->

                </div>
            </div>

            <div class="col-sm-9 padding-right">
                <div class="features_items"><!--features_items-->
                    <h2 class="title text-center"><?= $category->name ?></h2>
                    <div class="row">

                        <?php if(!empty($products)): ?>
                            <?php $i = 0; foreach($products as $product): ?>
                                <?php $i++; if($i%3 === 0): ?>
                                    <div class="row">
                                <?php endif; ?>
                                <div class="col-sm-4">
                                    <div class="product-image-wrapper">
                                        <div class="single-products">
                                            <div class="productinfo text-center">
                                                <?=Html::img('@web/images/products/' . $product->img, ['alt' => $product->name])?>
                                                <h2>$<?= $product->price ?></h2>
                                                <p><a href="<?= Url::to(['product/view', 'id' => $product->id]) ?>"><?= $product->name ?></a></p>
                                                <a href="#" data-id="<?= $product->id ?>" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                            </div>
                                            <?php if($product->new): ?>
                                                <?= Html::img("@web/images/home/new.png", ['alt' => 'Новинка', 'class' => 'new']) ?>
                                            <?php endif; ?>
                                            <?php if($product->sale): ?>
                                                <?= Html::img("@web/images/home/sale.png", ['alt' => 'Разпродажа', 'class' => 'new']) ?>
                                            <?php endif; ?>
                                        </div>
                                        <div class="choose">
                                            <ul class="nav nav-pills nav-justified">
                                                <li><a href=""><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                                                <li><a href=""><i class="fa fa-plus-square"></i>Add to compare</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <?php if($i%3 === 0): ?>
                                    </div>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <h2>Пока товаров нету!</h2>
                        <?php endif; ?>
                    </div>
                    <div class="row">
                        <?= LinkPager::widget([
                            'pagination' => $pages,
                        ]); ?>
                    </div>
                </div><!--features_items-->
            </div>
        </div>
    </div>
</section>